### ISSUE TITLE
[1.20.1 Forge] Crash with Supplementaries

### ISSUE THREAD

**Issue by MrKashew** [nicochart/AerialHell#8]
[latest (1).log](https://github.com/nicochart/AerialHell/files/13292795/latest.1.log)
[debug (2).log](https://github.com/nicochart/AerialHell/files/13292798/debug.2.log)
[crash-2023-11-05_19.04.31-client.txt](https://github.com/nicochart/AerialHell/files/13292800/crash-2023-11-05_19.04.31-client.txt)
Convo from Supplementaries Discord
https://discord.com/channels/790151253144895508/1170922703088259133
![image](https://github.com/nicochart/AerialHell/assets/53996665/563e6365-825b-4d6c-83d9-2d96ff9f3250)

**Comment by nicochart** [comment]
Thanks for your issue report.
Fixed the "sheets loaded too early" problem in the latest Aerial Hell 1.20.2-0.6.6 version :D

Supplementaries are not yet available for minecraft 1.20.2, so I can't test if the incompatibility is fully resolved..
But since they said the problem was with "sheets loaded too early", I consider this issue resolved
(don't hesitate to reopen one if the problem persists)

**Comment by PercyJames** [comment]
> Thanks for your issue report. Fixed the "sheets loaded too early" problem in the latest Aerial Hell 1.20.2-0.6.6 version :D
> 
> Supplementaries are not yet available for minecraft 1.20.2, so I can't test if the incompatibility is fully resolved.. But since they said the problem was with "sheets loaded too early", I consider this issue resolved (don't hesitate to reopen one if the problem persists)

Can you port this change to the 1.20.1 version?
